# Generated by Django 6.0.3 on 2026-03-09 06:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login', 'Login'), ('login_failed', 'Login Failed'), ('logout', 'Logout'), ('register', 'Register'), ('password_reset', 'Password Reset'), ('mfa_enabled', 'MFA Enabled'), ('mfa_disabled', 'MFA Disabled'), ('user_created', 'User Created'), ('user_role_changed', 'User Role Changed'), ('user_deleted', 'User Deleted'), ('consent_granted', 'Consent Granted'), ('consent_revoked', 'Consent Revoked'), ('medical_record_viewed', 'Medical Record Viewed'), ('medical_record_created', 'Medical Record Created'), ('medical_record_updated', 'Medical Record Updated'), ('emergency_access', 'Emergency Access')], db_index=True, max_length=30)),
                ('resource_type', models.CharField(blank=True, default='', help_text='Model / entity type affected, e.g. User, MedicalRecord', max_length=50)),
                ('resource_id', models.CharField(blank=True, default='', help_text='PK or identifier of the affected resource', max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('extra', models.JSONField(blank=True, default=dict, help_text='Arbitrary metadata')),
                ('actor', models.ForeignKey(blank=True, help_text='User who performed the action (null for anonymous / system)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'db_table': 'audit_logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['action', 'timestamp'], name='audit_logs_action_474804_idx'), models.Index(fields=['actor', 'timestamp'], name='audit_logs_actor_i_ce2144_idx'), models.Index(fields=['resource_type', 'timestamp'], name='audit_logs_resourc_4f6f11_idx')],
            },
        ),
    ]
