# Generated by Django 6.0.2 on 2026-02-08 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
        ('departments', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referral_id', models.CharField(db_index=True, max_length=20, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('priority', models.CharField(choices=[('routine', 'Routine'), ('urgent', 'Urgent'), ('emergency', 'Emergency')], default='routine', max_length=20)),
                ('reason', models.TextField(help_text='Reason for referral')),
                ('clinical_notes', models.TextField(blank=True, help_text='Additional clinical notes')),
                ('access_granted', models.BooleanField(default=False)),
                ('access_expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to='departments.department')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to='patients.patient')),
                ('referring_doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals_made', to='departments.doctor')),
                ('specialist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals_received', to='departments.doctor')),
            ],
            options={
                'db_table': 'referrals',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['referral_id'], name='referrals_referra_6eb13b_idx'), models.Index(fields=['patient', 'status'], name='referrals_patient_0fe9d4_idx'), models.Index(fields=['referring_doctor', 'status'], name='referrals_referri_b550a7_idx'), models.Index(fields=['specialist', 'status'], name='referrals_special_bb7495_idx')],
            },
        ),
    ]
