# Generated by Django 6.0.2 on 2026-02-25 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_rename_doctor_avai_doctor__5b1e57_idx_doctor_avai_doctor__faa50b_idx_and_more'),
        ('infection_tracking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='room',
            field=models.ForeignKey(blank=True, help_text='Room where the appointment takes place', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='infection_tracking.room'),
        ),
    ]
