# Generated by Django 6.0.2 on 2026-02-08 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WellnessTip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('hydration', 'Hydration'), ('nutrition', 'Nutrition'), ('exercise', 'Exercise'), ('sleep', 'Sleep'), ('mental', 'Mental Health'), ('general', 'General')], default='general', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'wellness_tips',
                'ordering': ['category', '-created_at'],
            },
        ),
    ]
