# Generated by Django 6.0.2 on 2026-02-08 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_user_users_email_4b85f2_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password_reset_expires',
            field=models.DateTimeField(blank=True, help_text='When the password reset token expires', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='password_reset_token',
            field=models.CharField(blank=True, help_text='Token for password reset (expires after 1 hour)', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('patient', 'Patient'), ('doctor', 'Doctor'), ('provider', 'Healthcare Provider'), ('admin', 'Administrator')], default='patient', help_text='User role in the system', max_length=20),
        ),
    ]
