# Generated by Django 6.0.2 on 2026-03-05 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('patient', 'Patient'), ('doctor', 'Doctor'), ('provider', 'Healthcare Provider'), ('pharmacist', 'Pharmacist'), ('lab_technician', 'Lab Technician'), ('admin', 'Administrator')], default='patient', help_text='User role in the system', max_length=20),
        ),
    ]
