# Generated by Django 6.0.2 on 2026-02-10 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('appointments', '0001_initial'),
        ('medical_records', '0008_prescription_override_reason_druginteraction_and_more'),
        ('labs', '0001_initial'),
    ]

    operations = [
        # Authentication indexes
        migrations.RunSQL(
            sql="CREATE INDEX IF NOT EXISTS auth_user_email_idx ON users(email);",
            reverse_sql="DROP INDEX IF EXISTS auth_user_email_idx;",
        ),
        migrations.RunSQL(
            sql="CREATE INDEX IF NOT EXISTS auth_user_role_idx ON users(role);",
            reverse_sql="DROP INDEX IF EXISTS auth_user_role_idx;",
        ),
        
        # Appointment indexes
        migrations.RunSQL(
            sql="CREATE INDEX IF NOT EXISTS appt_date_status_idx ON appointments(appointment_date, status);",
            reverse_sql="DROP INDEX IF EXISTS appt_date_status_idx;",
        ),
        migrations.RunSQL(
            sql="CREATE INDEX IF NOT EXISTS appt_doctor_date_idx ON appointments(doctor_id, appointment_date);",
            reverse_sql="DROP INDEX IF EXISTS appt_doctor_date_idx;",
        ),
        migrations.RunSQL(
            sql="CREATE INDEX IF NOT EXISTS appt_patient_date_idx ON appointments(patient_id, appointment_date);",
            reverse_sql="DROP INDEX IF EXISTS appt_patient_date_idx;",
        ),
        
        # Medical records indexes
        migrations.RunSQL(
            sql="CREATE INDEX IF NOT EXISTS med_rec_patient_date_idx ON medical_records(patient_id, created_at);",
            reverse_sql="DROP INDEX IF EXISTS med_rec_patient_date_idx;",
        ),

        
        # Lab orders indexes
        migrations.RunSQL(
            sql="CREATE INDEX IF NOT EXISTS lab_order_status_idx ON labs_laborder(status, created_at);",
            reverse_sql="DROP INDEX IF EXISTS lab_order_status_idx;",
        ),
        migrations.RunSQL(
            sql="CREATE INDEX IF NOT EXISTS lab_order_patient_idx ON labs_laborder(patient_id, created_at);",
            reverse_sql="DROP INDEX IF EXISTS lab_order_patient_idx;",
        ),
    ]
