# Generated by Django 6.0.3 on 2026-03-06 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemedicine', '0004_triagerequest_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnatomyRegionExplainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('summary', models.TextField()),
                ('details', models.JSONField(blank=True, default=list)),
                ('common_symptoms', models.JSONField(blank=True, default=list)),
                ('related_condition_ids', models.JSONField(blank=True, default=list)),
                ('warning_signals', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'anatomy_region_explainers',
                'ordering': ['region_id'],
                'indexes': [models.Index(fields=['region_id', 'is_active'], name='anatomy_reg_region__82e6a1_idx')],
            },
        ),
        migrations.CreateModel(
            name='ConditionCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('overview', models.TextField()),
                ('regions', models.JSONField(blank=True, default=list)),
                ('typical_symptoms', models.JSONField(blank=True, default=list)),
                ('seek_care_rules', models.JSONField(blank=True, default=list)),
                ('scope', models.CharField(db_index=True, default='top20', max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'condition_catalog',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['scope', 'is_active'], name='condition_c_scope_af0a49_idx'), models.Index(fields=['condition_id', 'is_active'], name='condition_c_conditi_d56a17_idx')],
            },
        ),
        migrations.CreateModel(
            name='ConditionPin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin_id', models.CharField(max_length=64)),
                ('region_id', models.CharField(max_length=64)),
                ('label', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=10)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pins', to='telemedicine.conditioncatalog')),
            ],
            options={
                'db_table': 'condition_pins',
                'ordering': ['sort_order', 'id'],
                'indexes': [models.Index(fields=['condition', 'region_id'], name='condition_p_conditi_b4ef83_idx')],
                'unique_together': {('condition', 'pin_id')},
            },
        ),
    ]
