# Generated by Django 6.0.3 on 2026-03-09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemedicine', '0005_anatomyregionexplainer_conditioncatalog_conditionpin'),
    ]

    operations = [
        migrations.AddField(
            model_name='conditioncatalog',
            name='pain_interpretations',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='conditioncatalog',
            name='region_pain_levels',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]

