# Generated by Django 6.0.2 on 2026-02-07 15:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique room identifier for joining', unique=True)),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('active', 'Active'), ('ended', 'Ended'), ('cancelled', 'Cancelled')], default='waiting', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, help_text='When the call actually started', null=True)),
                ('ended_at', models.DateTimeField(blank=True, help_text='When the call ended', null=True)),
                ('scheduled_for', models.DateTimeField(blank=True, help_text='Scheduled start time for the call', null=True)),
                ('reason', models.TextField(blank=True, help_text='Reason for the consultation')),
                ('doctor', models.ForeignKey(help_text='The doctor hosting this consultation', on_delete=django.db.models.deletion.CASCADE, related_name='doctor_video_rooms', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(help_text='The patient for this consultation', on_delete=django.db.models.deletion.CASCADE, related_name='patient_video_rooms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'video_rooms',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RoomParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('doctor', 'Doctor'), ('patient', 'Patient')], max_length=10)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('is_in_waiting_room', models.BooleanField(default=True, help_text='Whether participant is in waiting room')),
                ('is_admitted', models.BooleanField(default=False, help_text='Whether participant has been admitted to call')),
                ('connection_quality', models.IntegerField(blank=True, help_text='1-5 rating of connection quality', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_participations', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='telemedicine.videoroom')),
            ],
            options={
                'db_table': 'room_participants',
                'ordering': ['-joined_at'],
            },
        ),
        migrations.AddIndex(
            model_name='videoroom',
            index=models.Index(fields=['room_id'], name='video_rooms_room_id_eee920_idx'),
        ),
        migrations.AddIndex(
            model_name='videoroom',
            index=models.Index(fields=['doctor', 'status'], name='video_rooms_doctor__a16f35_idx'),
        ),
        migrations.AddIndex(
            model_name='videoroom',
            index=models.Index(fields=['patient', 'status'], name='video_rooms_patient_9f90a4_idx'),
        ),
        migrations.AddIndex(
            model_name='videoroom',
            index=models.Index(fields=['status', 'created_at'], name='video_rooms_status_ec4f3f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='roomparticipant',
            unique_together={('room', 'user')},
        ),
    ]
