# Generated by Django 6.0.2 on 2026-02-10 19:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemedicine', '0002_conversation_message'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SignalingMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(help_text='Signal type: offer, answer, candidate', max_length=50)),
                ('payload', models.JSONField(help_text='The signaling data (SDP or ICE candidate)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(help_text='The video room this signal belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='signals', to='telemedicine.videoroom')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_signals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['room', 'created_at'], name='telemedicin_room_id_2285b0_idx')],
            },
        ),
    ]
