# Generated by Django 6.0.2 on 2026-02-07 10:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='consent',
            index=models.Index(fields=['patient', 'is_granted'], name='consents_co_patient_5a8c4a_idx'),
        ),
        migrations.AddIndex(
            model_name='consent',
            index=models.Index(fields=['department', 'is_granted'], name='consents_co_departm_8542c2_idx'),
        ),
    ]
