# Generated by Django 6.0.2 on 2026-02-08 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_records', '0004_medicalrecord_file'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VitalSign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heart_rate', models.IntegerField(help_text='Beats per minute (bpm)')),
                ('systolic_bp', models.IntegerField(help_text='Systolic Blood Pressure (mmHg)')),
                ('diastolic_bp', models.IntegerField(help_text='Diastolic Blood Pressure (mmHg)')),
                ('weight', models.FloatField(help_text='Weight in kg')),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vitals', to='patients.patient')),
            ],
            options={
                'db_table': 'vital_signs',
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['patient', 'recorded_at'], name='vital_signs_patient_a18c54_idx')],
            },
        ),
    ]
