# Generated by Django 6.0.2 on 2026-02-09 17:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_records', '0007_emergencyaccesslog_emergency_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='override_reason',
            field=models.TextField(blank=True, help_text='Reason for overriding interaction warning'),
        ),
        migrations.CreateModel(
            name='DrugInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drug_a', models.CharField(max_length=200)),
                ('drug_b', models.CharField(max_length=200)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High'), ('critical', 'Critical')], default='moderate', max_length=20)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'drug_interactions',
                'indexes': [models.Index(fields=['drug_a'], name='drug_intera_drug_a_f6807e_idx'), models.Index(fields=['drug_b'], name='drug_intera_drug_b_30f5d9_idx'), models.Index(fields=['severity'], name='drug_intera_severit_66c99e_idx')],
            },
        ),
        migrations.CreateModel(
            name='MedicationAdherenceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taken_at', models.DateTimeField(auto_now_add=True)),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adherence_logs', to='medical_records.prescription')),
                ('taken_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medication_adherence', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'medication_adherence_logs',
                'ordering': ['-taken_at'],
            },
        ),
        migrations.CreateModel(
            name='MedicationHistoryEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('started', 'Started'), ('stopped', 'Stopped'), ('dispensed', 'Dispensed'), ('cancelled', 'Cancelled')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(blank=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_events', to='medical_records.prescription')),
            ],
            options={
                'db_table': 'medication_history_events',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='PharmacyOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('fulfilled', 'Fulfilled'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('pickup_code', models.CharField(db_index=True, max_length=32, unique=True)),
                ('verification_notes', models.TextField(blank=True)),
                ('dispensed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fulfilled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fulfilled_pharmacy_orders', to=settings.AUTH_USER_MODEL)),
                ('prescription', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pharmacy_order', to='medical_records.prescription')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_pharmacy_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pharmacy_orders',
                'ordering': ['-created_at'],
            },
        ),
    ]
