# Generated by Django 6.0.2 on 2026-02-08 09:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LabTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('category', models.CharField(choices=[('Hematology', 'Hematology'), ('Chemistry', 'Chemistry'), ('Endocrine', 'Endocrine'), ('Urinalysis', 'Urinalysis'), ('Coagulation', 'Coagulation'), ('Microbiology', 'Microbiology'), ('Molecular', 'Molecular'), ('Other', 'Other')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('turnaround_time', models.CharField(help_text="e.g., '24 hours', '2-3 days'", max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='LabOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.CharField(choices=[('routine', 'Routine'), ('urgent', 'Urgent'), ('stat', 'STAT')], default='routine', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('clinical_notes', models.TextField(blank=True)),
                ('fasting_required', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordered_labs', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_orders', to=settings.AUTH_USER_MODEL)),
                ('items', models.ManyToManyField(related_name='orders', to='labs.labtest')),
            ],
        ),
        migrations.CreateModel(
            name='LabResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_value', models.CharField(max_length=255)),
                ('reference_range', models.CharField(blank=True, max_length=255)),
                ('units', models.CharField(blank=True, max_length=50)),
                ('flag', models.CharField(blank=True, help_text="e.g., 'High', 'Low', 'Critical'", max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('file_attachment', models.FileField(blank=True, null=True, upload_to='lab_results/')),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('technician_name', models.CharField(blank=True, max_length=255)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='labs.laborder')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labs.labtest')),
            ],
        ),
    ]
