# Generated by Django 6.0.2 on 2026-02-09 17:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_rename_doctor_avai_doctor__5b1e57_idx_doctor_avai_doctor__faa50b_idx_and_more'),
        ('labs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='laborder',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_orders', to='appointments.appointment'),
        ),
        migrations.AddField(
            model_name='laborder',
            name='sample_id',
            field=models.CharField(blank=True, db_index=True, max_length=32, unique=True),
        ),
        migrations.AddField(
            model_name='labresult',
            name='file_attachment_content_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='labresult',
            name='file_attachment_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='labresult',
            name='released_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='labresult',
            name='released_to_patient',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='labresult',
            name='technician',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_results', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='laborder',
            name='status',
            field=models.CharField(choices=[('ordered', 'Ordered'), ('collected', 'Collected'), ('processing', 'Processing'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('pending', 'Pending')], default='ordered', max_length=20),
        ),
        migrations.CreateModel(
            name='LabResultNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lab_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='labs.labresult')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'lab_result_notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read'], name='lab_result__user_id_e716ff_idx'), models.Index(fields=['created_at'], name='lab_result__created_b7953d_idx')],
            },
        ),
    ]
