# Generated by Django 6.0.2 on 2026-02-07 15:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_records', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prescription',
            options={'ordering': ['-created_at', 'medication_name']},
        ),
        migrations.AddField(
            model_name='prescription',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prescription',
            name='is_signed',
            field=models.BooleanField(default=False, help_text='Whether this prescription has been digitally signed'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='signature_hash',
            field=models.CharField(blank=True, help_text='SHA-256 hash of prescription content for integrity verification', max_length=64),
        ),
        migrations.AddField(
            model_name='prescription',
            name='signed_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when prescription was signed', null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='signed_by',
            field=models.ForeignKey(blank=True, help_text='Doctor who signed this prescription', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signed_prescriptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='prescription',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('signed', 'Signed'), ('dispensed', 'Dispensed'), ('cancelled', 'Cancelled')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='prescription',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
