# Generated by Django 6.0.2 on 2026-02-08 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_records', '0003_emergencyaccesslog'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrecord',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='medical_records/'),
        ),
    ]
