# Generated by Django 6.0.2 on 2026-02-09 05:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
        ('medical_records', '0005_vitalsign'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrecord',
            name='amendment_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='attested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='attested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attested_records', to='departments.doctor'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='is_attested',
            field=models.BooleanField(default=False, help_text='Whether this record has been clinically attested'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='parent_record',
            field=models.ForeignKey(blank=True, help_text='Original record if this is an amendment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='amendments', to='medical_records.medicalrecord'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='source',
            field=models.CharField(choices=[('provider', 'Healthcare Provider'), ('patient', 'Patient Reported'), ('device', 'Medical Device'), ('external', 'External System')], db_index=True, default='provider', max_length=20),
        ),
        migrations.AddField(
            model_name='medicalrecordaccess',
            name='action',
            field=models.CharField(choices=[('viewed', 'Viewed'), ('created', 'Created'), ('updated', 'Updated'), ('deleted', 'Deleted'), ('printed', 'Printed'), ('exported', 'Exported'), ('attested', 'Attested'), ('amended', 'Amended')], default='viewed', max_length=20),
        ),
        migrations.AddField(
            model_name='vitalsign',
            name='is_verified',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vitalsign',
            name='source',
            field=models.CharField(choices=[('clinical', 'Clinical Measurement'), ('patient', 'Patient Reported'), ('device', 'Remote Monitoring Device')], default='clinical', max_length=20),
        ),
        migrations.AddField(
            model_name='vitalsign',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_vitals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='medicalrecordaccess',
            name='access_reason',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
