# Generated by Django 6.0.2 on 2026-02-09 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_records', '0006_medicalrecord_amendment_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencyaccesslog',
            name='emergency_type',
            field=models.CharField(choices=[('life_threatening', 'Life Threatening'), ('urgent_care', 'Urgent Care'), ('critical_lab', 'Critical Lab Result'), ('other', 'Other')], default='other', max_length=30),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='private_notes',
            field=models.TextField(blank=True, help_text='Private clinical notes (not visible to patients)'),
        ),
    ]
