# Generated by Codex on 2026-03-07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_patient_current_medications'),
        ('medical_records', '0008_prescription_override_reason_druginteraction_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicationInteractionKnowledge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('combination_signature', models.CharField(db_index=True, max_length=600)),
                ('medications', models.JSONField(default=list)),
                ('combination_size', models.IntegerField(db_index=True, default=2)),
                ('side_effect', models.CharField(max_length=255)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High'), ('critical', 'Critical')], default='moderate', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('source', models.CharField(default='HODDI', max_length=100)),
                ('source_version', models.CharField(blank=True, max_length=50)),
                ('evidence', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'medication_interaction_knowledge',
                'indexes': [models.Index(fields=['combination_signature'], name='medication__combina_8c6cb8_idx'), models.Index(fields=['combination_size'], name='medication__combina_9bca47_idx'), models.Index(fields=['severity'], name='medication__severit_c8f35d_idx')],
                'unique_together': {('combination_signature', 'side_effect', 'source_version')},
            },
        ),
        migrations.CreateModel(
            name='MedicationSideEffect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medication_name', models.CharField(db_index=True, max_length=200)),
                ('side_effect', models.CharField(max_length=255)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High'), ('critical', 'Critical')], default='moderate', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('source', models.CharField(default='HODDI', max_length=100)),
                ('source_version', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'db_table': 'medication_side_effects',
                'indexes': [models.Index(fields=['medication_name'], name='medication__medicat_d60ff8_idx'), models.Index(fields=['severity'], name='medication__severit_53f9dd_idx')],
                'unique_together': {('medication_name', 'side_effect', 'source_version')},
            },
        ),
        migrations.CreateModel(
            name='MedicationInteractionReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger_event', models.CharField(default='manual', max_length=50)),
                ('medications', models.JSONField(default=list)),
                ('total_medications', models.IntegerField(default=0)),
                ('total_pairs_checked', models.IntegerField(default=0)),
                ('total_triplets_checked', models.IntegerField(default=0)),
                ('total_findings', models.IntegerField(default=0)),
                ('critical_count', models.IntegerField(default=0)),
                ('high_count', models.IntegerField(default=0)),
                ('moderate_count', models.IntegerField(default=0)),
                ('low_count', models.IntegerField(default=0)),
                ('source_version', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_interaction_reports', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interaction_reports', to='patients.patient')),
            ],
            options={
                'db_table': 'medication_interaction_reports',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['patient', 'created_at'], name='medication__patient_86ec71_idx')],
            },
        ),
        migrations.CreateModel(
            name='MedicationInteractionReportItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finding_type', models.CharField(default='interaction', max_length=20)),
                ('medications', models.JSONField(default=list)),
                ('combination_size', models.IntegerField(default=1)),
                ('side_effect', models.CharField(max_length=255)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High'), ('critical', 'Critical')], default='moderate', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('source', models.CharField(default='HODDI', max_length=100)),
                ('source_reference', models.CharField(blank=True, max_length=100)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='medical_records.medicationinteractionreport')),
            ],
            options={
                'db_table': 'medication_interaction_report_items',
                'indexes': [models.Index(fields=['severity'], name='medication__severit_19a7d2_idx'), models.Index(fields=['combination_size'], name='medication__combina_42894f_idx')],
            },
        ),
    ]
