# Generated by Codex on 2026-03-07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_records', '0009_medicationinteractionknowledge_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicationReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(db_index=True, max_length=100)),
                ('display_name', models.CharField(max_length=255)),
                ('normalized_name', models.CharField(db_index=True, max_length=255)),
                ('source', models.CharField(default='HODDI', max_length=100)),
            ],
            options={
                'db_table': 'medication_references',
                'indexes': [models.Index(fields=['normalized_name'], name='medication__normali_0dbf70_idx'), models.Index(fields=['identifier'], name='medication__identif_596c7c_idx')],
                'unique_together': {('identifier', 'normalized_name')},
            },
        ),
    ]
