# Generated by Django 6.0.3 on 2026-03-07 13:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_records', '0010_medicationreference'),
        ('patients', '0004_patient_current_medications'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicationInteractionReportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('trigger_event', models.CharField(default='manual_refresh', max_length=50)),
                ('candidate_medications', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], db_index=True, default='queued', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'medication_interaction_report_jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='medicationinteractionknowledge',
            new_name='medication__combina_cd916c_idx',
            old_name='medication__combina_8c6cb8_idx',
        ),
        migrations.RenameIndex(
            model_name='medicationinteractionknowledge',
            new_name='medication__combina_824dca_idx',
            old_name='medication__combina_9bca47_idx',
        ),
        migrations.RenameIndex(
            model_name='medicationinteractionknowledge',
            new_name='medication__severit_1d86bd_idx',
            old_name='medication__severit_c8f35d_idx',
        ),
        migrations.RenameIndex(
            model_name='medicationinteractionreport',
            new_name='medication__patient_c3fde3_idx',
            old_name='medication__patient_86ec71_idx',
        ),
        migrations.RenameIndex(
            model_name='medicationinteractionreportitem',
            new_name='medication__severit_462147_idx',
            old_name='medication__severit_19a7d2_idx',
        ),
        migrations.RenameIndex(
            model_name='medicationinteractionreportitem',
            new_name='medication__combina_36aeb9_idx',
            old_name='medication__combina_42894f_idx',
        ),
        migrations.RenameIndex(
            model_name='medicationreference',
            new_name='medication__normali_30c725_idx',
            old_name='medication__normali_0dbf70_idx',
        ),
        migrations.RenameIndex(
            model_name='medicationreference',
            new_name='medication__identif_f2e2d7_idx',
            old_name='medication__identif_596c7c_idx',
        ),
        migrations.RenameIndex(
            model_name='medicationsideeffect',
            new_name='medication__medicat_50ec3c_idx',
            old_name='medication__medicat_d60ff8_idx',
        ),
        migrations.RenameIndex(
            model_name='medicationsideeffect',
            new_name='medication__severit_27acaf_idx',
            old_name='medication__severit_53f9dd_idx',
        ),
        migrations.AddField(
            model_name='medicationinteractionreport',
            name='coverage_gap',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='medicationinteractionreport',
            name='evaluated_combination_depth',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='medicationinteractionreport',
            name='max_supported_combination_size',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='medicationinteractionreport',
            name='not_evaluated_depths',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='medicationinteractionreportjob',
            name='generated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_interaction_report_jobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='medicationinteractionreportjob',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interaction_report_jobs', to='patients.patient'),
        ),
        migrations.AddField(
            model_name='medicationinteractionreportjob',
            name='report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='medical_records.medicationinteractionreport'),
        ),
        migrations.AddIndex(
            model_name='medicationinteractionreportjob',
            index=models.Index(fields=['task_id'], name='medication__task_id_11efc4_idx'),
        ),
        migrations.AddIndex(
            model_name='medicationinteractionreportjob',
            index=models.Index(fields=['patient', 'created_at'], name='medication__patient_8d966c_idx'),
        ),
        migrations.AddIndex(
            model_name='medicationinteractionreportjob',
            index=models.Index(fields=['status', 'created_at'], name='medication__status_8da952_idx'),
        ),
    ]
