# Generated by Django 6.0.3 on 2026-03-09 08:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_records', '0011_medicationinteractionreportjob_and_more'),
        ('patients', '0004_patient_current_medications'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_ref', models.CharField(db_index=True, max_length=24, unique=True)),
                ('patient_name', models.CharField(max_length=200)),
                ('patient_age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('patient_phone', models.CharField(blank=True, max_length=20)),
                ('chief_complaint', models.TextField()),
                ('severity', models.CharField(choices=[('critical', 'Critical – Immediate'), ('urgent', 'Urgent'), ('moderate', 'Moderate'), ('low', 'Low / Non-urgent')], default='urgent', max_length=12)),
                ('known_conditions', models.TextField(blank=True)),
                ('allergies', models.TextField(blank=True)),
                ('location_description', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('triaging', 'Triaging'), ('in_treatment', 'In Treatment'), ('discharged', 'Discharged'), ('cancelled', 'Cancelled')], default='submitted', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_emergency_cases', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emergency_cases', to='patients.patient')),
            ],
            options={
                'db_table': 'emergency_cases',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['case_ref'], name='emergency_c_case_re_570a25_idx'), models.Index(fields=['status', 'severity', 'created_at'], name='emergency_c_status_44e969_idx')],
            },
        ),
    ]
