# Generated by Django 6.0.2 on 2026-02-09 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Average rating from patient reviews', max_digits=3),
        ),
        migrations.AddField(
            model_name='doctor',
            name='reviews',
            field=models.IntegerField(default=0, help_text='Total number of patient reviews'),
        ),
    ]
