# Generated by Django 6.0.2 on 2026-02-10 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_add_password_reset_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('patient', 'Patient'), ('doctor', 'Doctor'), ('provider', 'Healthcare Provider'), ('pharmacist', 'Pharmacist'), ('admin', 'Administrator')], default='patient', help_text='User role in the system', max_length=20),
        ),
    ]
