# Generated by Django 6.0.2 on 2026-02-25 13:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0002_add_doctor_rating_reviews'),
        ('patients', '0004_patient_current_medications'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_id', models.CharField(db_index=True, max_length=30, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('equipment_type', models.CharField(choices=[('ventilator', 'Ventilator'), ('xray_portable', 'Portable X-Ray'), ('ultrasound', 'Ultrasound Machine'), ('ecg', 'ECG Machine'), ('infusion_pump', 'Infusion Pump'), ('wheelchair', 'Wheelchair'), ('stretcher', 'Stretcher'), ('defibrillator', 'Defibrillator'), ('monitor', 'Patient Monitor'), ('suction', 'Suction Machine'), ('other', 'Other')], max_length=30)),
                ('serial_number', models.CharField(blank=True, max_length=100)),
                ('requires_sterilization', models.BooleanField(default=True)),
                ('last_sterilized_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment', to='departments.department')),
            ],
            options={
                'db_table': 'equipment',
                'ordering': ['equipment_id'],
            },
        ),
        migrations.CreateModel(
            name='InfectionReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_id', models.CharField(db_index=True, max_length=20, unique=True)),
                ('infection_name', models.CharField(db_index=True, help_text='e.g. MRSA, C. difficile, VRE, Klebsiella', max_length=200)),
                ('infection_code', models.CharField(blank=True, help_text='ICD-10 code for the infection', max_length=20)),
                ('category', models.CharField(choices=[('hai', 'Hospital-Acquired Infection'), ('cai', 'Community-Acquired Infection'), ('ssi', 'Surgical Site Infection'), ('uti', 'Urinary Tract Infection'), ('bsi', 'Bloodstream Infection'), ('pneumonia', 'Pneumonia'), ('gi', 'Gastrointestinal'), ('other', 'Other')], default='hai', help_text='Classification of infection origin', max_length=20)),
                ('diagnosed_at', models.DateTimeField(help_text='Exact timestamp of diagnosis')),
                ('severity', models.CharField(choices=[('mild', 'Mild'), ('moderate', 'Moderate'), ('severe', 'Severe'), ('critical', 'Critical')], default='moderate', max_length=20)),
                ('specimen_source', models.CharField(blank=True, help_text='e.g. blood, urine, wound swab, sputum', max_length=100)),
                ('antibiotic_resistance', models.JSONField(blank=True, default=list, help_text='List of antibiotics the organism is resistant to')),
                ('notes', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='infection_reports', to='patients.patient')),
                ('reported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_infections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'infection_reports',
                'ordering': ['-diagnosed_at'],
            },
        ),
        migrations.CreateModel(
            name='InfectionTrace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trace_id', models.CharField(db_index=True, max_length=20, unique=True)),
                ('infection_name', models.CharField(max_length=200)),
                ('transmission_path', models.JSONField(help_text='Serialized path from Neo4j: [{type, id, label, overlap_time}, ...]')),
                ('path_length', models.IntegerField(help_text='Number of hops in the transmission chain')),
                ('confidence_score', models.FloatField(default=0.0, help_text='0.0 to 1.0 — weighted by time proximity and path length')),
                ('vector_type', models.CharField(choices=[('shared_room', 'Shared Room'), ('shared_doctor', 'Shared Doctor'), ('shared_equipment', 'Shared Equipment'), ('indirect', 'Indirect Chain'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('detected', 'Detected'), ('investigating', 'Under Investigation'), ('confirmed', 'Confirmed'), ('dismissed', 'Dismissed')], db_index=True, default='detected', max_length=20)),
                ('investigation_notes', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('investigated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investigated_traces', to=settings.AUTH_USER_MODEL)),
                ('source_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_traces', to='infection_tracking.infectionreport')),
                ('target_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_traces', to='infection_tracking.infectionreport')),
            ],
            options={
                'db_table': 'infection_traces',
                'ordering': ['-detected_at'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.CharField(db_index=True, max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('room_type', models.CharField(choices=[('examination', 'Examination Room'), ('imaging', 'Imaging Suite'), ('icu', 'ICU'), ('ward', 'General Ward'), ('operating', 'Operating Theater'), ('lab', 'Laboratory'), ('emergency', 'Emergency Bay'), ('procedure', 'Procedure Room'), ('isolation', 'Isolation Room'), ('nicu', 'NICU'), ('dialysis', 'Dialysis Unit'), ('pharmacy', 'Pharmacy'), ('blood_bank', 'Blood Bank'), ('rehab', 'Rehabilitation'), ('radiology', 'Radiology Suite'), ('endoscopy', 'Endoscopy Suite'), ('cathlab', 'Catheterization Lab')], max_length=20)),
                ('floor', models.IntegerField()),
                ('building', models.CharField(max_length=100)),
                ('capacity', models.IntegerField(default=1, help_text='Max simultaneous patients')),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='low', help_text='Infection transmission risk level for this room type', max_length=20)),
                ('requires_sterilization', models.BooleanField(default=False, help_text='Whether room requires sterilization between patients')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='departments.department')),
            ],
            options={
                'db_table': 'rooms',
                'ordering': ['building', 'floor', 'room_id'],
            },
        ),
        migrations.CreateModel(
            name='EquipmentUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('sterilized_after', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_logs', to='infection_tracking.equipment')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_usage', to='patients.patient')),
                ('used_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment_usage', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment_usage', to='infection_tracking.room')),
            ],
            options={
                'db_table': 'equipment_usage_logs',
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddField(
            model_name='equipment',
            name='current_room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment', to='infection_tracking.room'),
        ),
        migrations.CreateModel(
            name='RoomRiskScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(help_text='0.0 to 1.0 — higher means more cross-patient traffic')),
                ('patient_count', models.IntegerField(help_text='Number of unique patients in this room during the window')),
                ('doctor_count', models.IntegerField(help_text='Number of unique doctors working in this room during the window')),
                ('infection_count', models.IntegerField(default=0, help_text='Number of infections linked to this room during the window')),
                ('window_start', models.DateTimeField()),
                ('window_end', models.DateTimeField()),
                ('computed_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_scores', to='infection_tracking.room')),
            ],
            options={
                'db_table': 'room_risk_scores',
                'ordering': ['-computed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='infectionreport',
            index=models.Index(fields=['report_id'], name='infection_r_report__f3ce2b_idx'),
        ),
        migrations.AddIndex(
            model_name='infectionreport',
            index=models.Index(fields=['infection_name', 'diagnosed_at'], name='infection_r_infecti_f4e5a2_idx'),
        ),
        migrations.AddIndex(
            model_name='infectionreport',
            index=models.Index(fields=['patient', 'diagnosed_at'], name='infection_r_patient_63f953_idx'),
        ),
        migrations.AddIndex(
            model_name='infectionreport',
            index=models.Index(fields=['category'], name='infection_r_categor_7d951f_idx'),
        ),
        migrations.AddIndex(
            model_name='infectionreport',
            index=models.Index(fields=['severity'], name='infection_r_severit_0f18e4_idx'),
        ),
        migrations.AddIndex(
            model_name='infectiontrace',
            index=models.Index(fields=['trace_id'], name='infection_t_trace_i_1c8ebf_idx'),
        ),
        migrations.AddIndex(
            model_name='infectiontrace',
            index=models.Index(fields=['infection_name', 'status'], name='infection_t_infecti_3db37a_idx'),
        ),
        migrations.AddIndex(
            model_name='infectiontrace',
            index=models.Index(fields=['detected_at'], name='infection_t_detecte_2d74a6_idx'),
        ),
        migrations.AddIndex(
            model_name='infectiontrace',
            index=models.Index(fields=['vector_type'], name='infection_t_vector__5aa9e1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='infectiontrace',
            unique_together={('source_report', 'target_report')},
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['room_id'], name='rooms_room_id_331bb5_idx'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['room_type'], name='rooms_room_ty_7b8350_idx'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['risk_level'], name='rooms_risk_le_d5e5ee_idx'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['department', 'is_active'], name='rooms_departm_9c816b_idx'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['building', 'floor'], name='rooms_buildin_fefc2e_idx'),
        ),
        migrations.AddIndex(
            model_name='equipmentusagelog',
            index=models.Index(fields=['equipment', 'started_at'], name='equipment_u_equipme_97d3dd_idx'),
        ),
        migrations.AddIndex(
            model_name='equipmentusagelog',
            index=models.Index(fields=['patient', 'started_at'], name='equipment_u_patient_f400af_idx'),
        ),
        migrations.AddIndex(
            model_name='equipmentusagelog',
            index=models.Index(fields=['room', 'started_at'], name='equipment_u_room_id_09e548_idx'),
        ),
        migrations.AddIndex(
            model_name='equipment',
            index=models.Index(fields=['equipment_id'], name='equipment_equipme_c08382_idx'),
        ),
        migrations.AddIndex(
            model_name='equipment',
            index=models.Index(fields=['equipment_type'], name='equipment_equipme_f4cc15_idx'),
        ),
        migrations.AddIndex(
            model_name='equipment',
            index=models.Index(fields=['current_room'], name='equipment_current_b92866_idx'),
        ),
        migrations.AddIndex(
            model_name='roomriskscore',
            index=models.Index(fields=['room', 'computed_at'], name='room_risk_s_room_id_cd8174_idx'),
        ),
        migrations.AddIndex(
            model_name='roomriskscore',
            index=models.Index(fields=['score'], name='room_risk_s_score_a1132b_idx'),
        ),
        migrations.AddIndex(
            model_name='roomriskscore',
            index=models.Index(fields=['window_start', 'window_end'], name='room_risk_s_window__0ec68e_idx'),
        ),
    ]
