# Generated by Django 6.0.2 on 2026-02-09 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_doctor_availability_slot'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='doctoravailabilityslot',
            new_name='doctor_avai_doctor__faa50b_idx',
            old_name='doctor_avai_doctor__5b1e57_idx',
        ),
        migrations.RenameIndex(
            model_name='doctoravailabilityslot',
            new_name='doctor_avai_date_f9d200_idx',
            old_name='doctor_avai_date_st_4e57e2_idx',
        ),
    ]
