# Generated by Django 6.0.1 on 2026-01-30 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='laborder',
            name='clinical_notes',
            field=models.TextField(blank=True, help_text='Reason for order'),
        ),
        migrations.AddField(
            model_name='laborder',
            name='priority',
            field=models.CharField(choices=[('ROUTINE', 'Routine'), ('URGENT', 'Urgent'), ('STAT', 'STAT')], default='ROUTINE', max_length=10),
        ),
        migrations.AddField(
            model_name='labresult',
            name='file_hash',
            field=models.CharField(blank=True, help_text='SHA-256 hash of original file', max_length=64),
        ),
        migrations.AddField(
            model_name='notification',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
